Exerciselist.create(exercise: "ab crunch machine", muscle: "abdominals")
Exerciselist.create(exercise: "ab roller", muscle: "abdominals")
Exerciselist.create(exercise: "adductor", muscle: "adductors")
Exerciselist.create(exercise: "adductor/groin", muscle: "adductors")
Exerciselist.create(exercise: "advanced kettlebell windmill", muscle: "abdominals")
Exerciselist.create(exercise: "air bike", muscle: "abdominals")
Exerciselist.create(exercise: "all fours quad stretch", muscle: "quadriceps")
Exerciselist.create(exercise: "alternate hammer curl", muscle: "biceps")
Exerciselist.create(exercise: "alternate heel touchers", muscle: "abdominals")
Exerciselist.create(exercise: "alternate incline dumbbell curl", muscle: "biceps")
Exerciselist.create(exercise: "alternate leg diagonal bound", muscle: "quadriceps")
Exerciselist.create(exercise: "alternating cable shoulder press", muscle: "shoulders")
Exerciselist.create(exercise: "alternating deltoid raise", muscle: "shoulders")
Exerciselist.create(exercise: "alternating floor press", muscle: "chest")
Exerciselist.create(exercise: "alternating hang clean", muscle: "hamstrings")
Exerciselist.create(exercise: "alternating kettlebell press", muscle: "shoulders")
Exerciselist.create(exercise: "alternating kettlebell row", muscle: "middle back")
Exerciselist.create(exercise: "alternating renegade row",  muscle: "middle back")
Exerciselist.create(exercise: "ankle circles", muscle: "calves")
Exerciselist.create(exercise: "ankle on the knee", muscle: "glutes")
Exerciselist.create(exercise: "anterior tibialis-smr", muscle: "calves")
Exerciselist.create(exercise: "anti-gravity press", muscle: "shoulders")
Exerciselist.create(exercise: "arm circles", muscle: "shoulders")
Exerciselist.create(exercise: "arnold dumbbell press", muscle: "shoulders")
Exerciselist.create(exercise: "around the worlds", muscle: "chest")
Exerciselist.create(exercise: "atlas stone trainer",  muscle: "lower back")
Exerciselist.create(exercise: "atlas stones",  muscle: "lower back")
Exerciselist.create(exercise: "axle deadlift",  muscle: "lower back")
Exerciselist.create(exercise: "ab crunch machine", muscle: "abdominals")
Exerciselist.create(exercise: "ab roller", muscle: "abdominals")
Exerciselist.create(exercise: "adductor", muscle: "adductors")
Exerciselist.create(exercise: "adductor/groin", muscle: "adductors")
Exerciselist.create(exercise: "advanced kettlebell windmill", muscle: "abdominals")
Exerciselist.create(exercise: "air bike", muscle: "abdominals")
Exerciselist.create(exercise: "all fours quad stretch", muscle: "quadriceps")
Exerciselist.create(exercise: "alternate hammer curl", muscle: "biceps")
Exerciselist.create(exercise: "alternate heel touchers", muscle: "abdominals")
Exerciselist.create(exercise: "alternate incline dumbbell curl", muscle: "biceps")
Exerciselist.create(exercise: "alternate leg diagonal bound", muscle: "quadriceps")
Exerciselist.create(exercise: "alternating cable shoulder press", muscle: "shoulders")
Exerciselist.create(exercise: "alternating deltoid raise", muscle: "shoulders")
Exerciselist.create(exercise: "alternating floor press", muscle: "chest")
Exerciselist.create(exercise: "alternating hang clean", muscle: "hamstrings")
Exerciselist.create(exercise: "alternating kettlebell press", muscle: "shoulders")
Exerciselist.create(exercise: "alternating kettlebell row",  muscle: "middle back")
Exerciselist.create(exercise: "alternating renegade row",  muscle: "middle back")
Exerciselist.create(exercise: "ankle circles", muscle: "calves")
Exerciselist.create(exercise: "ankle on the knee", muscle: "glutes")
Exerciselist.create(exercise: "anterior tibialis-smr", muscle: "calves")
Exerciselist.create(exercise: "anti-gravity press", muscle: "shoulders")
Exerciselist.create(exercise: "arm circles", muscle: "shoulders")
Exerciselist.create(exercise: "arnold dumbbell press", muscle: "shoulders")
Exerciselist.create(exercise: "around the worlds", muscle: "chest")
Exerciselist.create(exercise: "atlas stone trainer",  muscle: "lower back")
Exerciselist.create(exercise: "atlas stones", muscle: "lower back")
Exerciselist.create(exercise: "axle deadlift",  muscle: "lower back")
Exerciselist.create(exercise: "back flyes - with bands", muscle: "shoulders")
Exerciselist.create(exercise: "backward drag", muscle: "quadriceps")
Exerciselist.create(exercise: "backward medicine ball throw", muscle: "shoulders")
Exerciselist.create(exercise: "balance board", muscle: "calves")
Exerciselist.create(exercise: "ball leg curl", muscle: "hamstrings")
Exerciselist.create(exercise: "band assisted pull-up", muscle: "lats")
Exerciselist.create(exercise: "band good morning", muscle: "hamstrings")
Exerciselist.create(exercise: "band good morning (pull through)", muscle: "hamstrings")
Exerciselist.create(exercise: "band hip adductions", muscle: "adductors")
Exerciselist.create(exercise: "band pull apart", muscle: "shoulders")
Exerciselist.create(exercise: "band skull crusher", muscle: "triceps")
Exerciselist.create(exercise: "barbell ab rollout", muscle: "abdominals")
Exerciselist.create(exercise: "barbell ab rollout - on knees", muscle: "abdominals")
Exerciselist.create(exercise: "barbell bench press - medium grip", muscle: "chest")
Exerciselist.create(exercise: "barbell curl", muscle: "biceps")
Exerciselist.create(exercise: "barbell curls lying against an incline", muscle: "biceps")
Exerciselist.create(exercise: "barbell deadlift", muscle: "lower back")
Exerciselist.create(exercise: "barbell full squat", muscle: "quadriceps")
Exerciselist.create(exercise: "barbell glute bridge", muscle: "glutes")
Exerciselist.create(exercise: "barbell guillotine bench press", muscle: "chest")
Exerciselist.create(exercise: "barbell hack squat", muscle: "quadriceps")
Exerciselist.create(exercise: "barbell hip thrust", muscle: "glutes")
Exerciselist.create(exercise: "barbell incline bench press medium grip", muscle: "chest")
Exerciselist.create(exercise: "barbell incline shoulder raise", muscle: "shoulders")
Exerciselist.create(exercise: "barbell lunge", muscle: "quadriceps")
Exerciselist.create(exercise: "barbell rear delt row", muscle: "shoulders")
Exerciselist.create(exercise: "barbell rollout from bench", muscle: "abdominals")
Exerciselist.create(exercise: "barbell seated calf raise", muscle: "calves")
Exerciselist.create(exercise: "barbell shoulder press", muscle: "shoulders")
Exerciselist.create(exercise: "barbell shrug", muscle: "traps")
Exerciselist.create(exercise: "barbell shrug behind the back", muscle: "traps")
Exerciselist.create(exercise: "barbell side bend", muscle: "abdominals")
Exerciselist.create(exercise: "barbell side split squat", muscle: "quadriceps")
Exerciselist.create(exercise: "barbell squat", muscle: "quadriceps")
Exerciselist.create(exercise: "barbell squat to a bench", muscle: "quadriceps")
Exerciselist.create(exercise: "barbell step ups", muscle: "quadriceps")
Exerciselist.create(exercise: "barbell walking lunge", muscle: "quadriceps")
Exerciselist.create(exercise: "battling ropes", muscle: "shoulders")
Exerciselist.create(exercise: "bear crawl sled drags", muscle: "quadriceps")
Exerciselist.create(exercise: "behind head chest stretch", muscle: "chest")
Exerciselist.create(exercise: "bench dips", muscle: "triceps")
Exerciselist.create(exercise: "bench jump", muscle: "quadriceps")
Exerciselist.create(exercise: "bench press - powerlifting", muscle: "triceps")
Exerciselist.create(exercise: "bench press - with bands", muscle: "chest")
Exerciselist.create(exercise: "bench press with chains", muscle: "triceps")
Exerciselist.create(exercise: "bench sprint", muscle: "quadriceps")
Exerciselist.create(exercise: "bent over barbell row",  muscle: "middle back")
Exerciselist.create(exercise: "bent over dumbbell rear delt raise with head on bench", muscle: "shoulders")
Exerciselist.create(exercise: "bent over low-pulley side lateral", muscle: "shoulders")
Exerciselist.create(exercise: "bent over one-arm long bar row",  muscle: "middle back")
Exerciselist.create(exercise: "bent over two-arm long bar row",  muscle: "middle back")
Exerciselist.create(exercise: "bent over two-dumbbell row",  muscle: "middle back")
Exerciselist.create(exercise: "bent over two-dumbbell row with palms in",  muscle: "middle back")
Exerciselist.create(exercise: "bent press", muscle: "abdominals")
Exerciselist.create(exercise: "bent-arm barbell pullover", muscle: "lats")
Exerciselist.create(exercise: "bent-arm dumbbell pullover", muscle: "chest")
Exerciselist.create(exercise: "bent-knee hip raise", muscle: "abdominals")
Exerciselist.create(exercise: "bicycling", muscle: "quadriceps")
Exerciselist.create(exercise: "bicycling, stationary", muscle: "quadriceps")
Exerciselist.create(exercise: "board press", muscle: "triceps")
Exerciselist.create(exercise: "body tricep press", muscle: "triceps")
Exerciselist.create(exercise: "body-up", muscle: "triceps")
Exerciselist.create(exercise: "bodyweight flyes", muscle: "chest")
Exerciselist.create(exercise: "bodyweight mid row",  muscle: "middle back")
Exerciselist.create(exercise: "bodyweight squat", muscle: "quadriceps")
Exerciselist.create(exercise: "bodyweight walking lunge", muscle: "quadriceps")
Exerciselist.create(exercise: "bosu ball cable crunch with side bends", muscle: "abdominals")
Exerciselist.create(exercise: "bottoms up", muscle: "abdominals")
Exerciselist.create(exercise: "bottoms-up clean from the hang position", muscle: "forearms")
Exerciselist.create(exercise: "box jump (multiple response)", muscle: "hamstrings")
Exerciselist.create(exercise: "box skip", muscle: "hamstrings")
Exerciselist.create(exercise: "box squat", muscle: "quadriceps")
Exerciselist.create(exercise: "box squat with bands", muscle: "quadriceps")
Exerciselist.create(exercise: "box squat with chains", muscle: "quadriceps")
Exerciselist.create(exercise: "brachialis-smr", muscle: "biceps")
Exerciselist.create(exercise: "bradford/rocky presses", muscle: "shoulders")
Exerciselist.create(exercise: "butt lift (bridge)", muscle: "glutes")
Exerciselist.create(exercise: "butt-ups", muscle: "abdominals")
Exerciselist.create(exercise: "butterfly", muscle: "chest")
Exerciselist.create(exercise: "cable chest press", muscle: "chest")
Exerciselist.create(exercise: "cable crossover", muscle: "chest")
Exerciselist.create(exercise: "cable crunch", muscle: "abdominals")
Exerciselist.create(exercise: "cable deadlifts", muscle: "quadriceps")
Exerciselist.create(exercise: "cable hammer curls - rope attachment", muscle: "biceps")
Exerciselist.create(exercise: "cable hip adduction", muscle: "quadriceps")
Exerciselist.create(exercise: "cable incline pushdown", muscle: "lats")
Exerciselist.create(exercise: "cable incline triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "cable internal rotation", muscle: "shoulders")
Exerciselist.create(exercise: "cable iron cross", muscle: "chest")
Exerciselist.create(exercise: "cable judo flip", muscle: "abdominals")
Exerciselist.create(exercise: "cable lying triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "cable one arm tricep extension", muscle: "triceps")
Exerciselist.create(exercise: "cable preacher curl", muscle: "biceps")
Exerciselist.create(exercise: "cable rear delt fly", muscle: "shoulders")
Exerciselist.create(exercise: "cable reverse crunch", muscle: "abdominals")
Exerciselist.create(exercise: "cable rope overhead triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "cable rope rear-delt rows", muscle: "shoulders")
Exerciselist.create(exercise: "cable russian twists", muscle: "abdominals")
Exerciselist.create(exercise: "cable seated crunch", muscle: "abdominals")
Exerciselist.create(exercise: "cable seated lateral raise", muscle: "shoulders")
Exerciselist.create(exercise: "cable shoulder press", muscle: "shoulders")
Exerciselist.create(exercise: "cable shrugs", muscle: "traps")
Exerciselist.create(exercise: "cable tuck reverse crunch", muscle: "abdominals")
Exerciselist.create(exercise: "cable wrist curl", muscle: "forearms")
Exerciselist.create(exercise: "calf press", muscle: "calves")
Exerciselist.create(exercise: "calf press on the leg press machine", muscle: "calves")
Exerciselist.create(exercise: "calf raise on a dumbbell", muscle: "calves")
Exerciselist.create(exercise: "calf raises - with bands", muscle: "calves")
Exerciselist.create(exercise: "calf stretch elbows against wall", muscle: "calves")
Exerciselist.create(exercise: "calf stretch hands against wall", muscle: "calves")
Exerciselist.create(exercise: "calf-machine shoulder shrug", muscle: "traps")
Exerciselist.create(exercise: "calves-smr", muscle: "calves")
Exerciselist.create(exercise: "car deadlift", muscle: "quadriceps")
Exerciselist.create(exercise: "car drivers", muscle: "shoulders")
Exerciselist.create(exercise: "carioca quick step", muscle: "adductors")
Exerciselist.create(exercise: "cat stretch",  muscle: "back")
Exerciselist.create(exercise: "catch and overhead throw", muscle: "lats")
Exerciselist.create(exercise: "chain handle extension", muscle: "triceps")
Exerciselist.create(exercise: "chain press", muscle: "chest")
Exerciselist.create(exercise: "chair leg extended stretch", muscle: "hamstrings")
Exerciselist.create(exercise: "chair lower back stretch", muscle: "lats")
Exerciselist.create(exercise: "chair squat", muscle: "quadriceps")
Exerciselist.create(exercise: "chair upper body stretch", muscle: "shoulders")
Exerciselist.create(exercise: "chest and front of shoulder stretch", muscle: "chest")
Exerciselist.create(exercise: "chest push (multiple response)", muscle: "chest")
Exerciselist.create(exercise: "chest push (single response)", muscle: "chest")
Exerciselist.create(exercise: "chest push from 3 point stance", muscle: "chest")
Exerciselist.create(exercise: "chest push with run release", muscle: "chest")
Exerciselist.create(exercise: "chest stretch on stability ball", muscle: "chest")
Exerciselist.create(exercise: "childs pose", muscle: "back")
Exerciselist.create(exercise: "chin to chest stretch", muscle: "neck")
Exerciselist.create(exercise: "chin-up", muscle: "lats")
Exerciselist.create(exercise: "circus bell", muscle: "shoulders")
Exerciselist.create(exercise: "clean", muscle: "hamstrings")
Exerciselist.create(exercise: "clean and jerk", muscle: "shoulders")
Exerciselist.create(exercise: "clean and press", muscle: "shoulders")
Exerciselist.create(exercise: "clean deadlift", muscle: "hamstrings")
Exerciselist.create(exercise: "clean from blocks", muscle: "quadriceps")
Exerciselist.create(exercise: "clean pull", muscle: "quadriceps")
Exerciselist.create(exercise: "clean shrug", muscle: "traps")
Exerciselist.create(exercise: "clock push-up", muscle: "chest")
Exerciselist.create(exercise: "close-grip barbell bench press", muscle: "triceps")
Exerciselist.create(exercise: "close-grip dumbbell press", muscle: "triceps")
Exerciselist.create(exercise: "close-grip ez bar curl", muscle: "biceps")
Exerciselist.create(exercise: "close-grip ez-bar curl with band", muscle: "biceps")
Exerciselist.create(exercise: "close-grip ez-bar press", muscle: "triceps")
Exerciselist.create(exercise: "close-grip front lat pulldown", muscle: "lats")
Exerciselist.create(exercise: "close-grip push-up off of a dumbbell", muscle: "triceps")
Exerciselist.create(exercise: "close-grip standing barbell curl", muscle: "biceps")
Exerciselist.create(exercise: "cocoons", muscle: "abdominals")
Exerciselist.create(exercise: "conans wheel", muscle: "quadriceps")
Exerciselist.create(exercise: "concentration curls", muscle: "biceps")
Exerciselist.create(exercise: "cross body hammer curl", muscle: "biceps")
Exerciselist.create(exercise: "cross over - with bands", muscle: "chest")
Exerciselist.create(exercise: "cross-body crunch", muscle: "abdominals")
Exerciselist.create(exercise: "crossover reverse lunge", muscle: "lower back")
Exerciselist.create(exercise: "crucifix", muscle: "shoulders")
Exerciselist.create(exercise: "crunch - hands overhead", muscle: "abdominals")
Exerciselist.create(exercise: "crunch - legs on exercise ball", muscle: "abdominals")
Exerciselist.create(exercise: "crunches", muscle: "abdominals")
Exerciselist.create(exercise: "cuban press", muscle: "shoulders")
Exerciselist.create(exercise: "dancers stretch", muscle: "lower back")
Exerciselist.create(exercise: "deadlift with bands", muscle: "lower back")
Exerciselist.create(exercise: "deadlift with chains", muscle: "lower back")
Exerciselist.create(exercise: "decline barbell bench press", muscle: "chest")
Exerciselist.create(exercise: "decline close-grip bench to skull crusher", muscle: "triceps")
Exerciselist.create(exercise: "decline crunch", muscle: "abdominals")
Exerciselist.create(exercise: "decline dumbbell bench press", muscle: "chest")
Exerciselist.create(exercise: "decline dumbbell flyes", muscle: "chest")
Exerciselist.create(exercise: "decline dumbbell triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "decline ez bar triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "decline oblique crunch", muscle: "abdominals")
Exerciselist.create(exercise: "decline push-up", muscle: "chest")
Exerciselist.create(exercise: "decline reverse crunch", muscle: "abdominals")
Exerciselist.create(exercise: "decline smith press", muscle: "chest")
Exerciselist.create(exercise: "deficit deadlift", muscle: "lower back")
Exerciselist.create(exercise: "depth jump leap", muscle: "quadriceps")
Exerciselist.create(exercise: "dip machine", muscle: "triceps")
Exerciselist.create(exercise: "dips - chest version", muscle: "chest")
Exerciselist.create(exercise: "dips - triceps version", muscle: "triceps")
Exerciselist.create(exercise: "donkey calf raises", muscle: "calves")
Exerciselist.create(exercise: "double kettlebell alternating hang clean", muscle: "hamstrings")
Exerciselist.create(exercise: "double kettlebell jerk", muscle: "shoulders")
Exerciselist.create(exercise: "double kettlebell push press", muscle: "shoulders")
Exerciselist.create(exercise: "double kettlebell snatch", muscle: "shoulders")
Exerciselist.create(exercise: "double kettlebell windmill", muscle: "abdominals")
Exerciselist.create(exercise: "double leg butt kick", muscle: "quadriceps")
Exerciselist.create(exercise: "downward facing balance", muscle: "glutes")
Exerciselist.create(exercise: "drag curl", muscle: "biceps")
Exerciselist.create(exercise: "drop push", muscle: "chest")
Exerciselist.create(exercise: "dumbbell alternate bicep curl", muscle: "biceps")
Exerciselist.create(exercise: "dumbbell bench press", muscle: "chest")
Exerciselist.create(exercise: "dumbbell bench press with neutral grip", muscle: "chest")
Exerciselist.create(exercise: "dumbbell bicep curl", muscle: "biceps")
Exerciselist.create(exercise: "dumbbell clean", muscle: "hamstrings")
Exerciselist.create(exercise: "dumbbell floor press", muscle: "triceps")
Exerciselist.create(exercise: "dumbbell flyes", muscle: "chest")
Exerciselist.create(exercise: "dumbbell incline row",  muscle: "middle back")
Exerciselist.create(exercise: "dumbbell incline shoulder raise", muscle: "shoulders")
Exerciselist.create(exercise: "dumbbell lunges", muscle: "quadriceps")
Exerciselist.create(exercise: "dumbbell lying one-arm rear lateral raise", muscle: "shoulders")
Exerciselist.create(exercise: "dumbbell lying pronation", muscle: "forearms")
Exerciselist.create(exercise: "dumbbell lying rear lateral raise", muscle: "shoulders")
Exerciselist.create(exercise: "dumbbell lying supination", muscle: "forearms")
Exerciselist.create(exercise: "dumbbell one-arm shoulder press", muscle: "shoulders")
Exerciselist.create(exercise: "dumbbell one-arm triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "dumbbell one-arm upright row", muscle: "shoulders")
Exerciselist.create(exercise: "dumbbell prone incline curl", muscle: "biceps")
Exerciselist.create(exercise: "dumbbell raise", muscle: "shoulders")
Exerciselist.create(exercise: "dumbbell rear lunge", muscle: "quadriceps")
Exerciselist.create(exercise: "dumbbell scaption", muscle: "shoulders")
Exerciselist.create(exercise: "dumbbell seated box jump", muscle: "quadriceps")
Exerciselist.create(exercise: "dumbbell seated one-leg calf raise", muscle: "calves")
Exerciselist.create(exercise: "dumbbell shoulder press", muscle: "shoulders")
Exerciselist.create(exercise: "dumbbell shrug", muscle: "traps")
Exerciselist.create(exercise: "dumbbell side bend", muscle: "abdominals")
Exerciselist.create(exercise: "dumbbell squat", muscle: "quadriceps")
Exerciselist.create(exercise: "dumbbell squat to a bench", muscle: "quadriceps")
Exerciselist.create(exercise: "dumbbell step ups", muscle: "quadriceps")
Exerciselist.create(exercise: "dumbbell tricep extension -pronated grip", muscle: "triceps")
Exerciselist.create(exercise: "dynamic back stretch", muscle: "lats")
Exerciselist.create(exercise: "dynamic chest stretch", muscle: "chest")
Exerciselist.create(exercise: "elbow circles", muscle: "shoulders")
Exerciselist.create(exercise: "elbow to knee", muscle: "abdominals")
Exerciselist.create(exercise: "elbows back", muscle: "chest")
Exerciselist.create(exercise: "elevated back lunge", muscle: "quadriceps")
Exerciselist.create(exercise: "elevated cable rows", muscle: "lats")
Exerciselist.create(exercise: "elliptical trainer", muscle: "quadriceps")
Exerciselist.create(exercise: "exercise ball crunch", muscle: "abdominals")
Exerciselist.create(exercise: "exercise ball pull-in", muscle: "abdominals")
Exerciselist.create(exercise: "extended range one-arm kettlebell floor press", muscle: "chest")
Exerciselist.create(exercise: "external rotation", muscle: "shoulders")
Exerciselist.create(exercise: "external rotation with band", muscle: "shoulders")
Exerciselist.create(exercise: "external rotation with cable", muscle: "shoulders")
Exerciselist.create(exercise: "ez-bar curl", muscle: "biceps")
Exerciselist.create(exercise: "ez-bar skullcrusher", muscle: "triceps")
Exerciselist.create(exercise: "face pull", muscle: "shoulders")
Exerciselist.create(exercise: "farmers walk", muscle: "forearms")
Exerciselist.create(exercise: "fast skipping", muscle: "quadriceps")
Exerciselist.create(exercise: "finger curls", muscle: "forearms")
Exerciselist.create(exercise: "flat bench cable flyes", muscle: "chest")
Exerciselist.create(exercise: "flat bench leg pull-in", muscle: "abdominals")
Exerciselist.create(exercise: "flat bench lying leg raise", muscle: "abdominals")
Exerciselist.create(exercise: "flexor incline dumbbell curls", muscle: "biceps")
Exerciselist.create(exercise: "floor glute-ham raise", muscle: "hamstrings")
Exerciselist.create(exercise: "floor press", muscle: "triceps")
Exerciselist.create(exercise: "floor press with chains", muscle: "triceps")
Exerciselist.create(exercise: "flutter kicks", muscle: "glutes")
Exerciselist.create(exercise: "foot-smr", muscle: "calves")
Exerciselist.create(exercise: "forward drag with press", muscle: "chest")
Exerciselist.create(exercise: "frankenstein squat", muscle: "quadriceps")
Exerciselist.create(exercise: "freehand jump squat", muscle: "quadriceps")
Exerciselist.create(exercise: "frog hops", muscle: "quadriceps")
Exerciselist.create(exercise: "frog sit-ups", muscle: "abdominals")
Exerciselist.create(exercise: "front barbell squat", muscle: "quadriceps")
Exerciselist.create(exercise: "front barbell squat to a bench", muscle: "quadriceps")
Exerciselist.create(exercise: "front box jump", muscle: "hamstrings")
Exerciselist.create(exercise: "front cable raise", muscle: "shoulders")
Exerciselist.create(exercise: "front cone hops (or hurdle hops)", muscle: "quadriceps")
Exerciselist.create(exercise: "front dumbbell raise", muscle: "shoulders")
Exerciselist.create(exercise: "front incline dumbbell raise", muscle: "shoulders")
Exerciselist.create(exercise: "front leg raises", muscle: "hamstrings")
Exerciselist.create(exercise: "front plate raise", muscle: "shoulders")
Exerciselist.create(exercise: "front raise and pullover", muscle: "chest")
Exerciselist.create(exercise: "front squat (clean grip)", muscle: "quadriceps")
Exerciselist.create(exercise: "front squats with two kettlebells", muscle: "quadriceps")
Exerciselist.create(exercise: "front two-dumbbell raise", muscle: "shoulders")
Exerciselist.create(exercise: "full range-of-motion lat pulldown", muscle: "lats")
Exerciselist.create(exercise: "gironda sternum chins", muscle: "lats")
Exerciselist.create(exercise: "glute ham raise", muscle: "hamstrings")
Exerciselist.create(exercise: "glute kickback", muscle: "glutes")
Exerciselist.create(exercise: "goblet squat", muscle: "quadriceps")
Exerciselist.create(exercise: "good morning", muscle: "hamstrings")
Exerciselist.create(exercise: "good morning off pins", muscle: "hamstrings")
Exerciselist.create(exercise: "gorilla chin/crunch", muscle: "abdominals")
Exerciselist.create(exercise: "groin and back stretch", muscle: "adductors")
Exerciselist.create(exercise: "groiners", muscle: "adductors")
Exerciselist.create(exercise: "hack squat", muscle: "quadriceps")
Exerciselist.create(exercise: "hammer curls", muscle: "biceps")
Exerciselist.create(exercise: "hammer grip incline db bench press", muscle: "chest")
Exerciselist.create(exercise: "hamstring stretch", muscle: "hamstrings")
Exerciselist.create(exercise: "hamstring-smr", muscle: "hamstrings")
Exerciselist.create(exercise: "handstand push-ups", muscle: "shoulders")
Exerciselist.create(exercise: "hang clean", muscle: "quadriceps")
Exerciselist.create(exercise: "hang clean - below the knees", muscle: "quadriceps")
Exerciselist.create(exercise: "hang snatch", muscle: "hamstrings")
Exerciselist.create(exercise: "hang snatch - below knees", muscle: "hamstrings")
Exerciselist.create(exercise: "hanging bar good morning", muscle: "hamstrings")
Exerciselist.create(exercise: "hanging leg raise", muscle: "abdominals")
Exerciselist.create(exercise: "hanging pike", muscle: "abdominals")
Exerciselist.create(exercise: "heaving snatch balance", muscle: "quadriceps")
Exerciselist.create(exercise: "heavy bag thrust", muscle: "chest")
Exerciselist.create(exercise: "high cable curls", muscle: "biceps")
Exerciselist.create(exercise: "hip circles (prone)", muscle: "abductors")
Exerciselist.create(exercise: "hip extension with bands", muscle: "glutes")
Exerciselist.create(exercise: "hip flexion with band", muscle: "quadriceps")
Exerciselist.create(exercise: "hip lift with band", muscle: "glutes")
Exerciselist.create(exercise: "hug a ball", muscle: "lower back")
Exerciselist.create(exercise: "hug knees to chest", muscle: "lower back")
Exerciselist.create(exercise: "hurdle hops", muscle: "hamstrings")
Exerciselist.create(exercise: "hyperextensions (back extensions)", muscle: "lower back")
Exerciselist.create(exercise: "hyperextensions with no hyperextension bench", muscle: "lower back")
Exerciselist.create(exercise: "iliotibial tract-smr", muscle: "abductors")
Exerciselist.create(exercise: "incline barbell triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "incline bench pull",  muscle: "middle back")
Exerciselist.create(exercise: "incline cable chest press", muscle: "chest")
Exerciselist.create(exercise: "incline cable flye", muscle: "chest")
Exerciselist.create(exercise: "incline dumbbell bench with palms facing in", muscle: "chest")
Exerciselist.create(exercise: "incline dumbbell curl", muscle: "biceps")
Exerciselist.create(exercise: "incline dumbbell flyes", muscle: "chest")
Exerciselist.create(exercise: "incline dumbbell flyes - with a twist", muscle: "chest")
Exerciselist.create(exercise: "incline dumbbell press", muscle: "chest")
Exerciselist.create(exercise: "incline hammer curls", muscle: "biceps")
Exerciselist.create(exercise: "incline inner biceps curl", muscle: "biceps")
Exerciselist.create(exercise: "incline push-up", muscle: "chest")
Exerciselist.create(exercise: "incline push-up close-grip", muscle: "triceps")
Exerciselist.create(exercise: "incline push-up depth jump", muscle: "chest")
Exerciselist.create(exercise: "incline push-up medium", muscle: "chest")
Exerciselist.create(exercise: "incline push-up reverse grip", muscle: "chest")
Exerciselist.create(exercise: "incline push-up wide", muscle: "chest")
Exerciselist.create(exercise: "intermediate groin stretch", muscle: "hamstrings")
Exerciselist.create(exercise: "intermediate hip flexor and quad stretch", muscle: "quadriceps")
Exerciselist.create(exercise: "internal rotation with band", muscle: "shoulders")
Exerciselist.create(exercise: "inverted row",  muscle: "middle back")
Exerciselist.create(exercise: "inverted row with straps",  muscle: "middle back")
Exerciselist.create(exercise: "iron cross", muscle: "shoulders")
Exerciselist.create(exercise: "iron crosses (stretch)", muscle: "quadriceps")
Exerciselist.create(exercise: "isometric chest squeezes", muscle: "chest")
Exerciselist.create(exercise: "isometric neck exercise - front and back", muscle: "neck")
Exerciselist.create(exercise: "isometric neck exercise - sides", muscle: "neck")
Exerciselist.create(exercise: "isometric wipers", muscle: "chest")
Exerciselist.create(exercise: "it band and glute stretch", muscle: "abductors")
Exerciselist.create(exercise: "jackknife sit-up", muscle: "abdominals")
Exerciselist.create(exercise: "janda sit-up", muscle: "abdominals")
Exerciselist.create(exercise: "jefferson squats", muscle: "quadriceps")
Exerciselist.create(exercise: "jerk balance", muscle: "shoulders")
Exerciselist.create(exercise: "jerk dip squat", muscle: "quadriceps")
Exerciselist.create(exercise: "jm press", muscle: "triceps")
Exerciselist.create(exercise: "jogging-treadmill", muscle: "quadriceps")
Exerciselist.create(exercise: "keg load", muscle: "lower back")
Exerciselist.create(exercise: "kettlebell arnold press", muscle: "shoulders")
Exerciselist.create(exercise: "kettlebell dead clean", muscle: "hamstrings")
Exerciselist.create(exercise: "kettlebell figure 8", muscle: "abdominals")
Exerciselist.create(exercise: "kettlebell hang clean", muscle: "hamstrings")
Exerciselist.create(exercise: "kettlebell one-legged deadlift", muscle: "hamstrings")
Exerciselist.create(exercise: "kettlebell pass between the legs", muscle: "abdominals")
Exerciselist.create(exercise: "kettlebell pirate ships", muscle: "shoulders")
Exerciselist.create(exercise: "kettlebell pistol squat", muscle: "quadriceps")
Exerciselist.create(exercise: "kettlebell seated press", muscle: "shoulders")
Exerciselist.create(exercise: "kettlebell seesaw press", muscle: "shoulders")
Exerciselist.create(exercise: "kettlebell sumo high pull", muscle: "traps")
Exerciselist.create(exercise: "kettlebell thruster", muscle: "shoulders")
Exerciselist.create(exercise: "kettlebell turkish get-up (lunge style)", muscle: "shoulders")
Exerciselist.create(exercise: "kettlebell turkish get-up (squat style)", muscle: "shoulders")
Exerciselist.create(exercise: "kettlebell windmill", muscle: "abdominals")
Exerciselist.create(exercise: "kipping muscle up", muscle: "lats")
Exerciselist.create(exercise: "knee across the body", muscle: "glutes")
Exerciselist.create(exercise: "knee circles", muscle: "calves")
Exerciselist.create(exercise: "knee tuck jump", muscle: "hamstrings")
Exerciselist.create(exercise: "knee/hip raise on parallel bars", muscle: "abdominals")
Exerciselist.create(exercise: "kneeling arm drill", muscle: "shoulders")
Exerciselist.create(exercise: "kneeling cable crunch with alternating oblique twists", muscle: "abdominals")
Exerciselist.create(exercise: "kneeling cable triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "kneeling forearm stretch", muscle: "forearms")
Exerciselist.create(exercise: "kneeling high pulley row", muscle: "lats")
Exerciselist.create(exercise: "kneeling hip flexor", muscle: "quadriceps")
Exerciselist.create(exercise: "kneeling jump squat", muscle: "glutes")
Exerciselist.create(exercise: "kneeling single-arm high pulley row", muscle: "lats")
Exerciselist.create(exercise: "kneeling squat", muscle: "glutes")
Exerciselist.create(exercise: "landmine 180s", muscle: "abdominals")
Exerciselist.create(exercise: "landmine linear jammer", muscle: "shoulders")
Exerciselist.create(exercise: "lateral bound", muscle: "adductors")
Exerciselist.create(exercise: "lateral box jump", muscle: "adductors")
Exerciselist.create(exercise: "lateral cone hops", muscle: "adductors")
Exerciselist.create(exercise: "lateral raise - with bands", muscle: "shoulders")
Exerciselist.create(exercise: "latissimus dorsi-smr", muscle: "lats")
Exerciselist.create(exercise: "leg extensions", muscle: "quadriceps")
Exerciselist.create(exercise: "leg lift", muscle: "glutes")
Exerciselist.create(exercise: "leg press", muscle: "quadriceps")
Exerciselist.create(exercise: "leg pull-in", muscle: "abdominals")
Exerciselist.create(exercise: "leg-over floor press", muscle: "chest")
Exerciselist.create(exercise: "leg-up hamstring stretch", muscle: "hamstrings")
Exerciselist.create(exercise: "leverage chest press", muscle: "chest")
Exerciselist.create(exercise: "leverage deadlift", muscle: "quadriceps")
Exerciselist.create(exercise: "leverage decline chest press", muscle: "chest")
Exerciselist.create(exercise: "leverage high row",  muscle: "middle back")
Exerciselist.create(exercise: "leverage incline chest press", muscle: "chest")
Exerciselist.create(exercise: "leverage iso row", muscle: "lats")
Exerciselist.create(exercise: "leverage shoulder press", muscle: "shoulders")
Exerciselist.create(exercise: "leverage shrug", muscle: "traps")
Exerciselist.create(exercise: "linear 3-part start technique", muscle: "hamstrings")
Exerciselist.create(exercise: "linear acceleration wall drill", muscle: "hamstrings")
Exerciselist.create(exercise: "linear depth jump", muscle: "quadriceps")
Exerciselist.create(exercise: "log lift", muscle: "shoulders")
Exerciselist.create(exercise: "london bridges", muscle: "lats")
Exerciselist.create(exercise: "looking at ceiling", muscle: "quadriceps")
Exerciselist.create(exercise: "low cable crossover", muscle: "chest")
Exerciselist.create(exercise: "low cable triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "low pulley row to neck", muscle: "shoulders")
Exerciselist.create(exercise: "lower back curl", muscle: "abdominals")
Exerciselist.create(exercise: "lower back-smr", muscle: "lower back")
Exerciselist.create(exercise: "lunge pass through", muscle: "hamstrings")
Exerciselist.create(exercise: "lunge sprint", muscle: "quadriceps")
Exerciselist.create(exercise: "lying bent leg groin", muscle: "adductors")
Exerciselist.create(exercise: "lying cable curl", muscle: "biceps")
Exerciselist.create(exercise: "lying cambered barbell row",  muscle: "middle back")
Exerciselist.create(exercise: "lying close-grip bar curl on high pulley", muscle: "biceps")
Exerciselist.create(exercise: "lying close-grip barbell triceps extension behind the head", muscle: "triceps")
Exerciselist.create(exercise: "lying close-grip barbell triceps press to chin", muscle: "triceps")
Exerciselist.create(exercise: "lying crossover", muscle: "abductors")
Exerciselist.create(exercise: "lying dumbbell tricep extension", muscle: "triceps")
Exerciselist.create(exercise: "lying face down plate neck resistance", muscle: "neck")
Exerciselist.create(exercise: "lying face up plate neck resistance", muscle: "neck")
Exerciselist.create(exercise: "lying glute", muscle: "glutes")
Exerciselist.create(exercise: "lying hamstring", muscle: "hamstrings")
Exerciselist.create(exercise: "lying high bench barbell curl", muscle: "biceps")
Exerciselist.create(exercise: "lying leg curls", muscle: "hamstrings")
Exerciselist.create(exercise: "lying machine squat", muscle: "quadriceps")
Exerciselist.create(exercise: "lying one-arm lateral raise", muscle: "shoulders")
Exerciselist.create(exercise: "lying prone quadriceps", muscle: "quadriceps")
Exerciselist.create(exercise: "lying rear delt raise", muscle: "shoulders")
Exerciselist.create(exercise: "lying supine dumbbell curl", muscle: "biceps")
Exerciselist.create(exercise: "lying t-bar row",  muscle: "middle back")
Exerciselist.create(exercise: "lying triceps press", muscle: "triceps")
Exerciselist.create(exercise: "machine bench press", muscle: "chest")
Exerciselist.create(exercise: "machine bicep curl", muscle: "biceps")
Exerciselist.create(exercise: "machine preacher curls", muscle: "biceps")
Exerciselist.create(exercise: "machine shoulder (military) press", muscle: "shoulders")
Exerciselist.create(exercise: "machine triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "medicine ball chest pass", muscle: "chest")
Exerciselist.create(exercise: "medicine ball full twist", muscle: "abdominals")
Exerciselist.create(exercise: "medicine ball scoop throw", muscle: "shoulders")
Exerciselist.create(exercise: " back shrug", muscle: "middle back")
Exerciselist.create(exercise: "middle back stretch", muscle: "middle back")
Exerciselist.create(exercise: "mixed grip chin", muscle: "middle back")
Exerciselist.create(exercise: "monster walk", muscle: "abductors")
Exerciselist.create(exercise: "mountain climbers", muscle: "quadriceps")
Exerciselist.create(exercise: "moving claw series", muscle: "hamstrings")
Exerciselist.create(exercise: "muscle snatch", muscle: "hamstrings")
Exerciselist.create(exercise: "muscle up", muscle: "lats")
Exerciselist.create(exercise: "narrow stance hack squats", muscle: "quadriceps")
Exerciselist.create(exercise: "narrow stance leg press", muscle: "quadriceps")
Exerciselist.create(exercise: "narrow stance squats", muscle: "quadriceps")
Exerciselist.create(exercise: "natural glute ham raise", muscle: "hamstrings")
Exerciselist.create(exercise: "neck press", muscle: "chest")
Exerciselist.create(exercise: "neck-smr", muscle: "neck")
Exerciselist.create(exercise: "oblique crunches", muscle: "abdominals")
Exerciselist.create(exercise: "oblique crunches - on the floor", muscle: "abdominals")
Exerciselist.create(exercise: "olympic squat", muscle: "quadriceps")
Exerciselist.create(exercise: "on your side quad stretch", muscle: "quadriceps")
Exerciselist.create(exercise: "on-your-back quad stretch", muscle: "quadriceps")
Exerciselist.create(exercise: "one arm against wall", muscle: "lats")
Exerciselist.create(exercise: "one arm chin-up", muscle: "middle back")
Exerciselist.create(exercise: "one arm dumbbell bench press", muscle: "chest")
Exerciselist.create(exercise: "one arm dumbbell preacher curl", muscle: "biceps")
Exerciselist.create(exercise: "one arm floor press", muscle: "triceps")
Exerciselist.create(exercise: "one arm lat pulldown", muscle: "lats")
Exerciselist.create(exercise: "one arm pronated dumbbell triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "one arm supinated dumbbell triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "one half locust", muscle: "quadriceps")
Exerciselist.create(exercise: "one handed hang", muscle: "lats")
Exerciselist.create(exercise: "one knee to chest", muscle: "glutes")
Exerciselist.create(exercise: "one leg barbell squat", muscle: "quadriceps")
Exerciselist.create(exercise: "one-arm dumbbell row", muscle: "middle back")
Exerciselist.create(exercise: "one-arm flat bench dumbbell flye", muscle: "chest")
Exerciselist.create(exercise: "one-arm high-pulley cable side bends", muscle: "abdominals")
Exerciselist.create(exercise: "one-arm incline lateral raise", muscle: "shoulders")
Exerciselist.create(exercise: "one-arm kettlebell clean", muscle: "hamstrings")
Exerciselist.create(exercise: "one-arm kettlebell clean and jerk", muscle: "shoulders")
Exerciselist.create(exercise: "one-arm kettlebell floor press", muscle: "chest")
Exerciselist.create(exercise: "one-arm kettlebell jerk", muscle: "shoulders")
Exerciselist.create(exercise: "one-arm kettlebell military press to the side", muscle: "shoulders")
Exerciselist.create(exercise: "one-arm kettlebell para press", muscle: "shoulders")
Exerciselist.create(exercise: "one-arm kettlebell push press", muscle: "shoulders")
Exerciselist.create(exercise: "one-arm kettlebell row", muscle: "middle back")
Exerciselist.create(exercise: "one-arm kettlebell snatch", muscle: "shoulders")
Exerciselist.create(exercise: "one-arm kettlebell split jerk", muscle: "shoulders")
Exerciselist.create(exercise: "one-arm kettlebell split snatch", muscle: "shoulders")
Exerciselist.create(exercise: "one-arm kettlebell swings", muscle: "hamstrings")
Exerciselist.create(exercise: "one-arm long bar row", muscle: "middle back")
Exerciselist.create(exercise: "one-arm medicine ball slam", muscle: "abdominals")
Exerciselist.create(exercise: "one-arm open palm kettlebell clean", muscle: "hamstrings")
Exerciselist.create(exercise: "one-arm overhead kettlebell squats", muscle: "quadriceps")
Exerciselist.create(exercise: "one-arm side deadlift", muscle: "quadriceps")
Exerciselist.create(exercise: "one-arm side laterals", muscle: "shoulders")
Exerciselist.create(exercise: "one-legged cable kickback", muscle: "glutes")
Exerciselist.create(exercise: "open palm kettlebell clean", muscle: "hamstrings")
Exerciselist.create(exercise: "otis-up", muscle: "abdominals")
Exerciselist.create(exercise: "overhead cable curl", muscle: "biceps")
Exerciselist.create(exercise: "overhead lat", muscle: "lats")
Exerciselist.create(exercise: "overhead slam", muscle: "lats")
Exerciselist.create(exercise: "overhead squat", muscle: "quadriceps")
Exerciselist.create(exercise: "overhead stretch", muscle: "abdominals")
Exerciselist.create(exercise: "overhead triceps", muscle: "triceps")
Exerciselist.create(exercise: "pallof press with rotation", muscle: "abdominals")
Exerciselist.create(exercise: "palms-down dumbbell wrist curl over a bench", muscle: "forearms")
Exerciselist.create(exercise: "palms-down wrist curl over a bench", muscle: "forearms")
Exerciselist.create(exercise: "palms-up barbell wrist curl over a bench", muscle: "forearms")
Exerciselist.create(exercise: "palms-up dumbbell wrist curl over a bench", muscle: "forearms")
Exerciselist.create(exercise: "parallel bar dip", muscle: "triceps")
Exerciselist.create(exercise: "pelvic tilt into bridge", muscle: "lower back")
Exerciselist.create(exercise: "peroneals stretch", muscle: "calves")
Exerciselist.create(exercise: "peroneals-smr", muscle: "calves")
Exerciselist.create(exercise: "physioball hip bridge", muscle: "glutes")
Exerciselist.create(exercise: "pin presses", muscle: "triceps")
Exerciselist.create(exercise: "piriformis-smr", muscle: "glutes")
Exerciselist.create(exercise: "plank", muscle: "abdominals")
Exerciselist.create(exercise: "plate pinch", muscle: "forearms")
Exerciselist.create(exercise: "plate twist", muscle: "abdominals")
Exerciselist.create(exercise: "platform hamstring slides", muscle: "hamstrings")
Exerciselist.create(exercise: "plie dumbbell squat", muscle: "quadriceps")
Exerciselist.create(exercise: "plyo kettlebell pushups", muscle: "chest")
Exerciselist.create(exercise: "plyo push-up", muscle: "chest")
Exerciselist.create(exercise: "posterior tibialis stretch", muscle: "calves")
Exerciselist.create(exercise: "power clean", muscle: "hamstrings")
Exerciselist.create(exercise: "power clean from blocks", muscle: "hamstrings")
Exerciselist.create(exercise: "power jerk", muscle: "quadriceps")
Exerciselist.create(exercise: "power partials", muscle: "shoulders")
Exerciselist.create(exercise: "power snatch", muscle: "hamstrings")
Exerciselist.create(exercise: "power snatch from blocks", muscle: "quadriceps")
Exerciselist.create(exercise: "power stairs", muscle: "hamstrings")
Exerciselist.create(exercise: "preacher curl", muscle: "biceps")
Exerciselist.create(exercise: "preacher hammer dumbbell curl", muscle: "biceps")
Exerciselist.create(exercise: "press sit-up", muscle: "abdominals")
Exerciselist.create(exercise: "prone manual hamstring", muscle: "hamstrings")
Exerciselist.create(exercise: "prowler sprint", muscle: "hamstrings")
Exerciselist.create(exercise: "pull through", muscle: "glutes")
Exerciselist.create(exercise: "pullups", muscle: "lats")
Exerciselist.create(exercise: "push press", muscle: "shoulders")
Exerciselist.create(exercise: "push press - behind the neck", muscle: "shoulders")
Exerciselist.create(exercise: "push up to side plank", muscle: "chest")
Exerciselist.create(exercise: "push-up wide", muscle: "chest")
Exerciselist.create(exercise: "push-ups - close triceps position", muscle: "triceps")
Exerciselist.create(exercise: "push-ups with feet elevated", muscle: "chest")
Exerciselist.create(exercise: "push-ups with feet on an exercise ball", muscle: "chest")
Exerciselist.create(exercise: "pushups", muscle: "chest")
Exerciselist.create(exercise: "pushups (close and wide hand positions)", muscle: "chest")
Exerciselist.create(exercise: "pyramid", muscle: "lower back")
Exerciselist.create(exercise: "quad stretch", muscle: "quadriceps")
Exerciselist.create(exercise: "quadriceps-smr", muscle: "quadriceps")
Exerciselist.create(exercise: "quick leap", muscle: "quadriceps")
Exerciselist.create(exercise: "rack delivery", muscle: "shoulders")
Exerciselist.create(exercise: "rack pull with bands", muscle: "lower back")
Exerciselist.create(exercise: "rack pulls", muscle: "lower back")
Exerciselist.create(exercise: "rear leg raises", muscle: "quadriceps")
Exerciselist.create(exercise: "recumbent bike", muscle: "quadriceps")
Exerciselist.create(exercise: "return push from stance", muscle: "shoulders")
Exerciselist.create(exercise: "reverse band bench press", muscle: "triceps")
Exerciselist.create(exercise: "reverse band box squat", muscle: "quadriceps")
Exerciselist.create(exercise: "reverse band deadlift", muscle: "lowerback")
Exerciselist.create(exercise: "reverse band power squat", muscle: "quadriceps")
Exerciselist.create(exercise: "reverse band sumo deadlift", muscle: "hamstrings")
Exerciselist.create(exercise: "reverse barbell curl", muscle: "biceps")
Exerciselist.create(exercise: "reverse barbell preacher curls", muscle: "biceps")
Exerciselist.create(exercise: "reverse cable curl", muscle: "biceps")
Exerciselist.create(exercise: "reverse crunch", muscle: "abdominals")
Exerciselist.create(exercise: "reverse flyes", muscle: "shoulders")
Exerciselist.create(exercise: "reverse flyes with external rotation", muscle: "shoulders")
Exerciselist.create(exercise: "reverse grip bent-over rows", muscle: "middle back")
Exerciselist.create(exercise: "reverse grip triceps pushdown", muscle: "triceps")
Exerciselist.create(exercise: "reverse hyperextension", muscle: "hamstrings")
Exerciselist.create(exercise: "reverse machine flyes", muscle: "shoulders")
Exerciselist.create(exercise: "reverse plate curls", muscle: "biceps")
Exerciselist.create(exercise: "reverse triceps bench press", muscle: "triceps")
Exerciselist.create(exercise: "rhomboids-smr", muscle: "middle back")
Exerciselist.create(exercise: "rickshaw carry", muscle: "forearms")
Exerciselist.create(exercise: "rickshaw deadlift", muscle: "quadriceps")
Exerciselist.create(exercise: "ring dips", muscle: "triceps")
Exerciselist.create(exercise: "rocket jump", muscle: "quadriceps")
Exerciselist.create(exercise: "rocking standing calf raise", muscle: "calves")
Exerciselist.create(exercise: "rocky pull-ups/pulldowns", muscle: "lats")
Exerciselist.create(exercise: "romanian deadlift", muscle: "hamstrings")
Exerciselist.create(exercise: "romanian deadlift from deficit", muscle: "hamstrings")
Exerciselist.create(exercise: "rope climb", muscle: "lats")
Exerciselist.create(exercise: "rope crunch", muscle: "abdominals")
Exerciselist.create(exercise: "rope jumping", muscle: "quadriceps")
Exerciselist.create(exercise: "rope straight-arm pulldown", muscle: "lats")
Exerciselist.create(exercise: "round the world shoulder stretch", muscle: "shoulders")
Exerciselist.create(exercise: "rowing, stationary", muscle: "quadriceps")
Exerciselist.create(exercise: "runners stretch", muscle: "hamstrings")
Exerciselist.create(exercise: "running, treadmill", muscle: "quadriceps")
Exerciselist.create(exercise: "russian twist", muscle: "abdominals")
Exerciselist.create(exercise: "sandbag load", muscle: "quadriceps")
Exerciselist.create(exercise: "scapular pull-up", muscle: "traps")
Exerciselist.create(exercise: "scissor kick", muscle: "abdominals")
Exerciselist.create(exercise: "scissors jump", muscle: "quadriceps")
Exerciselist.create(exercise: "seated band hamstring curl", muscle: "hamstrings")
Exerciselist.create(exercise: "seated barbell military press", muscle: "shoulders")
Exerciselist.create(exercise: "seated barbell twist", muscle: "abdominals")
Exerciselist.create(exercise: "seated bent-over one-arm dumbbell triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "seated bent-over rear delt raise", muscle: "shoulders")
Exerciselist.create(exercise: "seated bent-over two-arm dumbbell triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "seated biceps", muscle: "biceps")
Exerciselist.create(exercise: "seated cable rows", muscle: "middle back")
Exerciselist.create(exercise: "seated cable shoulder press", muscle: "shoulders")
Exerciselist.create(exercise: "seated calf raise", muscle: "calves")
Exerciselist.create(exercise: "seated calf stretch", muscle: "calves")
Exerciselist.create(exercise: "seated close-grip concentration barbell curl", muscle: "biceps")
Exerciselist.create(exercise: "seated dumbbell curl", muscle: "biceps")
Exerciselist.create(exercise: "seated dumbbell inner biceps curl", muscle: "biceps")
Exerciselist.create(exercise: "seated dumbbell palms-down wrist curl", muscle: "forearms")
Exerciselist.create(exercise: "seated dumbbell palms-up wrist curl", muscle: "forearms")
Exerciselist.create(exercise: "seated dumbbell press", muscle: "shoulders")
Exerciselist.create(exercise: "seated flat bench leg pull-in", muscle: "abdominals")
Exerciselist.create(exercise: "seated floor hamstring stretch", muscle: "hamstrings")
Exerciselist.create(exercise: "seated front deltoid", muscle: "shoulders")
Exerciselist.create(exercise: "seated glute", muscle: "glutes")
Exerciselist.create(exercise: "seated good mornings", muscle: "lower back")
Exerciselist.create(exercise: "seated hamstring", muscle: "hamstrings")
Exerciselist.create(exercise: "seated hamstring and calf stretch", muscle: "hamstrings")
Exerciselist.create(exercise: "seated head harness neck resistance", muscle: "neck")
Exerciselist.create(exercise: "seated leg curl", muscle: "hamstrings")
Exerciselist.create(exercise: "seated leg tucks", muscle: "abdominals")
Exerciselist.create(exercise: "seated one-arm cable pulley rows", muscle: "middle back")
Exerciselist.create(exercise: "seated one-arm dumbbell palms-down wrist curl", muscle: "forearms")
Exerciselist.create(exercise: "seated one-arm dumbbell palms-up wrist curl", muscle: "forearms")
Exerciselist.create(exercise: "seated overhead stretch", muscle: "abdominals")
Exerciselist.create(exercise: "seated palm-up barbell wrist curl", muscle: "forearms")
Exerciselist.create(exercise: "seated palms-down barbell wrist curl", muscle: "forearms")
Exerciselist.create(exercise: "seated side lateral raise", muscle: "shoulders")
Exerciselist.create(exercise: "seated triceps press", muscle: "triceps")
Exerciselist.create(exercise: "seated two-arm palms-up low-pulley wrist curl", muscle: "forearms")
Exerciselist.create(exercise: "see-saw press (alternating side press)", muscle: "shoulders")
Exerciselist.create(exercise: "shotgun row", muscle: "lats")
Exerciselist.create(exercise: "shoulder circles", muscle: "shoulders")
Exerciselist.create(exercise: "shoulder press - with bands", muscle: "shoulders")
Exerciselist.create(exercise: "shoulder raise", muscle: "shoulders")
Exerciselist.create(exercise: "shoulder stretch", muscle: "shoulders")
Exerciselist.create(exercise: "side bridge", muscle: "abdominals")
Exerciselist.create(exercise: "side hop-sprint", muscle: "quadriceps")
Exerciselist.create(exercise: "side jackknife", muscle: "abdominals")
Exerciselist.create(exercise: "side lateral raise", muscle: "shoulders")
Exerciselist.create(exercise: "side laterals to front raise", muscle: "shoulders")
Exerciselist.create(exercise: "side leg raises", muscle: "adductors")
Exerciselist.create(exercise: "side lying groin stretch", muscle: "adductors")
Exerciselist.create(exercise: "side neck stretch", muscle: "neck")
Exerciselist.create(exercise: "side standing long jump", muscle: "quadriceps")
Exerciselist.create(exercise: "side to side box shuffle", muscle: "quadriceps")
Exerciselist.create(exercise: "side to side chins", muscle: "lats")
Exerciselist.create(exercise: "side wrist pull", muscle: "shoulders")
Exerciselist.create(exercise: "side-lying floor stretch", muscle: "lats")
Exerciselist.create(exercise: "single dumbbell raise", muscle: "shoulders")
Exerciselist.create(exercise: "single leg butt kick", muscle: "quadriceps")
Exerciselist.create(exercise: "single leg glute bridge", muscle: "glutes")
Exerciselist.create(exercise: "single leg push-off", muscle: "quadriceps")
Exerciselist.create(exercise: "single-arm cable crossover", muscle: "chest")
Exerciselist.create(exercise: "single-arm linear jammer", muscle: "shoulders")
Exerciselist.create(exercise: "single-arm push-up", muscle: "chest")
Exerciselist.create(exercise: "single-cone sprint drill", muscle: "quadriceps")
Exerciselist.create(exercise: "single-leg high box squat", muscle: "quadriceps")
Exerciselist.create(exercise: "single-leg hop progression", muscle: "quadriceps")
Exerciselist.create(exercise: "single-leg lateral hop", muscle: "quadriceps")
Exerciselist.create(exercise: "single-leg leg extension", muscle: "quadriceps")
Exerciselist.create(exercise: "single-leg stride jump", muscle: "quadriceps")
Exerciselist.create(exercise: "sit squats", muscle: "quadriceps")
Exerciselist.create(exercise: "sit-up", muscle: "abdominals")
Exerciselist.create(exercise: "skating", muscle: "quadriceps")
Exerciselist.create(exercise: "sled drag - harness", muscle: "quadriceps")
Exerciselist.create(exercise: "sled overhead backward walk", muscle: "shoulders")
Exerciselist.create(exercise: "sled overhead triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "sled push", muscle: "quadriceps")
Exerciselist.create(exercise: "sled reverse flye", muscle: "shoulders")
Exerciselist.create(exercise: "sled row", muscle: "middle back")
Exerciselist.create(exercise: "sledgehammer swings", muscle: "abdominals")
Exerciselist.create(exercise: "smith incline shoulder raise", muscle: "shoulders")
Exerciselist.create(exercise: "smith machine behind the back shrug", muscle: "traps")
Exerciselist.create(exercise: "smith machine bench press", muscle: "chest")
Exerciselist.create(exercise: "smith machine bent over row", muscle: "middle back")
Exerciselist.create(exercise: "smith machine calf raise", muscle: "calves")
Exerciselist.create(exercise: "smith machine close-grip bench press", muscle: "triceps")
Exerciselist.create(exercise: "smith machine decline press", muscle: "chest")
Exerciselist.create(exercise: "smith machine hang power clean", muscle: "hamstrings")
Exerciselist.create(exercise: "smith machine hip raise", muscle: "abdominals")
Exerciselist.create(exercise: "smith machine incline bench press", muscle: "chest")
Exerciselist.create(exercise: "smith machine leg press", muscle: "quadriceps")
Exerciselist.create(exercise: "smith machine one-arm upright row", muscle: "shoulders")
Exerciselist.create(exercise: "smith machine overhead shoulder press", muscle: "shoulders")
Exerciselist.create(exercise: "smith machine pistol squat", muscle: "quadriceps")
Exerciselist.create(exercise: "smith machine reverse calf raises", muscle: "calves")
Exerciselist.create(exercise: "smith machine shrug", muscle: "traps")
Exerciselist.create(exercise: "smith machine squat", muscle: "quadriceps")
Exerciselist.create(exercise: "smith machine stiff-legged deadlift", muscle: "hamstrings")
Exerciselist.create(exercise: "smith machine upright row", muscle: "traps")
Exerciselist.create(exercise: "smith single-leg split squat", muscle: "quadriceps")
Exerciselist.create(exercise: "snatch", muscle: "quadriceps")
Exerciselist.create(exercise: "snatch balance", muscle: "quadriceps")
Exerciselist.create(exercise: "snatch deadlift", muscle: "hamstrings")
Exerciselist.create(exercise: "snatch from blocks", muscle: "quadriceps")
Exerciselist.create(exercise: "snatch pull", muscle: "hamstrings")
Exerciselist.create(exercise: "snatch shrug", muscle: "traps")
Exerciselist.create(exercise: "speed band overhead triceps", muscle: "triceps")
Exerciselist.create(exercise: "speed band pushdown", muscle: "triceps")
Exerciselist.create(exercise: "speed box squat", muscle: "quadriceps")
Exerciselist.create(exercise: "speed squats", muscle: "quadriceps")
Exerciselist.create(exercise: "spell caster", muscle: "abdominals")
Exerciselist.create(exercise: "spider crawl", muscle: "abdominals")
Exerciselist.create(exercise: "spider curl", muscle: "biceps")
Exerciselist.create(exercise: "spinal stretch", muscle: "middle back")
Exerciselist.create(exercise: "split clean", muscle: "quadriceps")
Exerciselist.create(exercise: "split jerk", muscle: "quadriceps")
Exerciselist.create(exercise: "split jump", muscle: "quadriceps")
Exerciselist.create(exercise: "split snatch", muscle: "hamstrings")
Exerciselist.create(exercise: "split squat with dumbbells", muscle: "quadriceps")
Exerciselist.create(exercise: "split squats", muscle: "hamstrings")
Exerciselist.create(exercise: "squat jerk", muscle: "quadriceps")
Exerciselist.create(exercise: "squat with bands", muscle: "quadriceps")
Exerciselist.create(exercise: "squat with chains", muscle: "quadriceps")
Exerciselist.create(exercise: "squat with plate movers", muscle: "quadriceps")
Exerciselist.create(exercise: "squats - with bands", muscle: "quadriceps")
Exerciselist.create(exercise: "stairmaster", muscle: "quadriceps")
Exerciselist.create(exercise: "standing alternating dumbbell press", muscle: "shoulders")
Exerciselist.create(exercise: "standing barbell calf raise", muscle: "calves")
Exerciselist.create(exercise: "standing barbell press behind neck", muscle: "shoulders")
Exerciselist.create(exercise: "standing bent-over one-arm dumbbell triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "standing bent-over two-arm dumbbell triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "standing biceps cable curl", muscle: "biceps")
Exerciselist.create(exercise: "standing biceps stretch", muscle: "biceps")
Exerciselist.create(exercise: "standing bradford press", muscle: "shoulders")
Exerciselist.create(exercise: "standing cable chest press", muscle: "chest")
Exerciselist.create(exercise: "standing cable lift", muscle: "abdominals")
Exerciselist.create(exercise: "standing cable wood chop", muscle: "abdominals")
Exerciselist.create(exercise: "standing calf raises", muscle: "calves")
Exerciselist.create(exercise: "standing concentration curl", muscle: "biceps")
Exerciselist.create(exercise: "standing dumbbell calf raise", muscle: "calves")
Exerciselist.create(exercise: "standing dumbbell press", muscle: "shoulders")
Exerciselist.create(exercise: "standing dumbbell reverse curl", muscle: "biceps")
Exerciselist.create(exercise: "standing dumbbell straight-arm front delt raise above head", muscle: "shoulders")
Exerciselist.create(exercise: "standing dumbbell triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "standing dumbbell upright row", muscle: "traps")
Exerciselist.create(exercise: "standing elevated quad stretch", muscle: "quadriceps")
Exerciselist.create(exercise: "standing front barbell raise over head", muscle: "shoulders")
Exerciselist.create(exercise: "standing gastrocnemius calf stretch", muscle: "calves")
Exerciselist.create(exercise: "standing hamstring and calf stretch", muscle: "hamstrings")
Exerciselist.create(exercise: "standing hip circles", muscle: "abductors")
Exerciselist.create(exercise: "standing hip flexors", muscle: "quadriceps")
Exerciselist.create(exercise: "standing inner-biceps curl", muscle: "biceps")
Exerciselist.create(exercise: "standing lateral stretch", muscle: "abdominals")
Exerciselist.create(exercise: "standing leg curl", muscle: "hamstrings")
Exerciselist.create(exercise: "standing long jump", muscle: "quadriceps")
Exerciselist.create(exercise: "standing low-pulley deltoid raise", muscle: "shoulders")
Exerciselist.create(exercise: "standing low-pulley one-arm triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "standing military press", muscle: "shoulders")
Exerciselist.create(exercise: "standing olympic plate hand squeeze", muscle: "forearms")
Exerciselist.create(exercise: "standing one-arm cable curl", muscle: "biceps")
Exerciselist.create(exercise: "standing one-arm dumbbell curl over incline bench", muscle: "biceps")
Exerciselist.create(exercise: "standing one-arm dumbbell triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "standing overhead barbell triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "standing palm-in one-arm dumbbell press", muscle: "shoulders")
Exerciselist.create(exercise: "standing palms-in dumbbell press", muscle: "shoulders")
Exerciselist.create(exercise: "standing palms-up barbell behind the back wrist curl", muscle: "forearms")
Exerciselist.create(exercise: "standing pelvic tilt", muscle: "lower back")
Exerciselist.create(exercise: "standing rope crunch", muscle: "abdominals")
Exerciselist.create(exercise: "standing soleus and achilles stretch", muscle: "calves")
Exerciselist.create(exercise: "standing toe touches", muscle: "hamstrings")
Exerciselist.create(exercise: "standing towel triceps extension", muscle: "triceps")
Exerciselist.create(exercise: "standing two-arm overhead throw", muscle: "shoulders")
Exerciselist.create(exercise: "star jump", muscle: "quadriceps")
Exerciselist.create(exercise: "step mill", muscle: "quadriceps")
Exerciselist.create(exercise: "step-up with knee raise", muscle: "glutes")
Exerciselist.create(exercise: "stiff leg barbell good morning", muscle: "lower back")
Exerciselist.create(exercise: "stiff-legged barbell deadlift", muscle: "hamstrings")
Exerciselist.create(exercise: "stiff-legged dumbbell deadlift", muscle: "hamstrings")
Exerciselist.create(exercise: "stomach vacuum", muscle: "abdominals")
Exerciselist.create(exercise: "straight bar bench mid rows", muscle: "middle back")
Exerciselist.create(exercise: "straight raises on incline bench", muscle: "shoulders")
Exerciselist.create(exercise: "straight-arm dumbbell pullover", muscle: "chest")
Exerciselist.create(exercise: "straight-arm pulldown", muscle: "lats")
Exerciselist.create(exercise: "stride jump crossover", muscle: "quadriceps")
Exerciselist.create(exercise: "sumo deadlift", muscle: "hamstrings")
Exerciselist.create(exercise: "sumo deadlift with bands", muscle: "hamstrings")
Exerciselist.create(exercise: "sumo deadlift with chains", muscle: "hamstrings")
Exerciselist.create(exercise: "superman", muscle: "lower back")
Exerciselist.create(exercise: "supine chest throw", muscle: "triceps")
Exerciselist.create(exercise: "supine one-arm overhead throw", muscle: "abdominals")
Exerciselist.create(exercise: "supine two-arm overhead throw", muscle: "abdominals")
Exerciselist.create(exercise: "suspended push-up", muscle: "chest")
Exerciselist.create(exercise: "suspended reverse crunch", muscle: "abdominals")
Exerciselist.create(exercise: "suspended row", muscle: "middle back")
Exerciselist.create(exercise: "suspended split squat", muscle: "quadriceps")
Exerciselist.create(exercise: "t-bar row with handle", muscle: "middle back")
Exerciselist.create(exercise: "tate press", muscle: "triceps")
Exerciselist.create(exercise: "the straddle", muscle: "hamstrings")
Exerciselist.create(exercise: "thigh abductor", muscle: "abductors")
Exerciselist.create(exercise: "thigh adductor", muscle: "adductors")
Exerciselist.create(exercise: "tire flip", muscle: "quadriceps")
Exerciselist.create(exercise: "toe touchers", muscle: "abdominals")
Exerciselist.create(exercise: "torso rotation", muscle: "abdominals")
Exerciselist.create(exercise: "trail running/walking", muscle: "quadriceps")
Exerciselist.create(exercise: "trap bar deadlift", muscle: "quadriceps")
Exerciselist.create(exercise: "tricep dumbbell kickback", muscle: "triceps")
Exerciselist.create(exercise: "tricep side stretch", muscle: "triceps")
Exerciselist.create(exercise: "triceps overhead extension with rope", muscle: "triceps")
Exerciselist.create(exercise: "triceps pushdown", muscle: "triceps")
Exerciselist.create(exercise: "triceps pushdown - rope attachment", muscle: "triceps")
Exerciselist.create(exercise: "triceps pushdown - v-bar attachment", muscle: "triceps")
Exerciselist.create(exercise: "triceps stretch", muscle: "triceps")
Exerciselist.create(exercise: "tuck crunch", muscle: "abdominals")
Exerciselist.create(exercise: "two-arm dumbbell preacher curl", muscle: "biceps")
Exerciselist.create(exercise: "two-arm kettlebell clean", muscle: "shoulders")
Exerciselist.create(exercise: "two-arm kettlebell jerk", muscle: "shoulders")
Exerciselist.create(exercise: "two-arm kettlebell military press", muscle: "shoulders")
Exerciselist.create(exercise: "two-arm kettlebell row", muscle: "middle back")
Exerciselist.create(exercise: "underhand cable pulldowns", muscle: "lats")
Exerciselist.create(exercise: "upper back stretch", muscle: "middle back")
Exerciselist.create(exercise: "upper back-leg grab", muscle: "hamstrings")
Exerciselist.create(exercise: "upright barbell row", muscle: "shoulders")
Exerciselist.create(exercise: "upright cable row", muscle: "traps")
Exerciselist.create(exercise: "upright row - with bands", muscle: "traps")
Exerciselist.create(exercise: "upward stretch", muscle: "shoulders")
Exerciselist.create(exercise: "v-bar pulldown", muscle: "lats")
Exerciselist.create(exercise: "v-bar pullup", muscle: "lats")
Exerciselist.create(exercise: "vertical swing", muscle: "hamstrings")
Exerciselist.create(exercise: "walking, treadmill", muscle: "quadriceps")
Exerciselist.create(exercise: "weighted ball hyperextension", muscle: "lower back")
Exerciselist.create(exercise: "weighted ball side bend", muscle: "abdominals")
Exerciselist.create(exercise: "weighted bench dip", muscle: "triceps")
Exerciselist.create(exercise: "weighted crunches", muscle: "abdominals")
Exerciselist.create(exercise: "weighted jump squat", muscle: "quadriceps")
Exerciselist.create(exercise: "weighted pull ups", muscle: "lats")
Exerciselist.create(exercise: "weighted sissy squat", muscle: "quadriceps")
Exerciselist.create(exercise: "weighted sit-ups - with bands", muscle: "abdominals")
Exerciselist.create(exercise: "weighted squat", muscle: "quadriceps")
Exerciselist.create(exercise: "wide stance barbell squat", muscle: "quadriceps")
Exerciselist.create(exercise: "wide stance stiff legs", muscle: "hamstrings")
Exerciselist.create(exercise: "wide-grip barbell bench press", muscle: "chest")
Exerciselist.create(exercise: "wide-grip decline barbell bench press", muscle: "chest")
Exerciselist.create(exercise: "wide-grip decline barbell pullover", muscle: "chest")
Exerciselist.create(exercise: "wide-grip lat pulldown", muscle: "lats")
Exerciselist.create(exercise: "wide-grip pulldown behind the neck", muscle: "lats")
Exerciselist.create(exercise: "wide-grip rear pull-up", muscle: "lats")
Exerciselist.create(exercise: "wide-grip standing barbell curl", muscle: "biceps")
Exerciselist.create(exercise: "wind sprints", muscle: "abdominals")
Exerciselist.create(exercise: "windmills", muscle: "abductors")
Exerciselist.create(exercise: "worlds greatest stretch", muscle: "hamstrings")
Exerciselist.create(exercise: "wrist circles", muscle: "forearms")
Exerciselist.create(exercise: "wrist roller", muscle: "forearms")
Exerciselist.create(exercise: "wrist rotations with straight bar", muscle: "forearms")
Exerciselist.create(exercise: "yoke walk", muscle: "quadriceps")
Exerciselist.create(exercise: "zercher squats", muscle: "quadriceps")
Exerciselist.create(exercise: "zottman curl", muscle: "biceps")
Exerciselist.create(exercise: "zottman preacher curl", muscle: "biceps")

Meal.create(meal: "BBQ CHICKEN WRAPPED ASPARAGUS", ingredients: "
CHICKEN 2-3 OZ THINLY CUT,
ASPARAGUS 12,
BBQ SAUCE 2 TBSP,
CUMIN, PAPRIKA, GARLIC, PEPPER,
BELL PEPPERS 1 CUP DICED,
BROWN RICE 1/2 CUP,
FRUIT OPTIONAL", directions: "Set oven to 405°F.
Measure and cut chicken breasts into thin, 2-3 oz pieces. Feel free to further flatten the chicken with a mallet.
Season chicken cutlets with 1 tbsp barbecue sauce (for each piece) and your choice of seasonings.
Chop the ends off asparagus and wrap the chicken around 6 asparagus spears.
Place the chicken on a baking sheet with the open facing down.
Bake in the oven for about 8-10 minutes.", user_id: 1)


Meal.create(meal: "	STUFFED MUSCLE EGGS WITH PITA BREAD", ingredients:"
WILD SALMON 1 CAN LOW SODIUM,
HARDBOILED EGGS 2,
GREEK YOGURT 1 TBSP,
SEASONING TO TASTE,
LETTUCE 1 LEAF,
CHERRY TOMATOES 5,
PITA POCKET 1/2 WHOLE,
GOAT CHEESE 1 TBSP,
MUSTARD
KUMQUATS", directions:"Boil 2 eggs. Peel them and slice them in half. Remove the yolk from 1 egg (or both eggs) and add to a bowl.
Add 1/2 can wild salmon to the bowl along with 1 tbsp Greek yogurt, onions, and your other choice of seasonings.
Mix the ingredients together; then stuff the eggs. Or, add egg whites to the mixture to create a salmon salad.
Eat the meal with pita bread or stuff the pita with the salad, lettuce, and tomatoes.", user_id: 1)

Meal.create(meal: "	WILD GAME AND BLACK BEAN STUFFED BELL PEPPER", ingredients: "
WILD GAME 6 OZ,
BLACK BEANS 1/2 CUP,
BELL PEPPERS 2,
SALSA 4 TBSP,
GOAT CHEESE 2 TBSP,
PARSLEY,
BROWN RICE 1/4 CUP,
PINEAPPLE,
", directions: "Set oven to 405°F.
Cut tops off bell peppers and remove the seeds inside.
Spray a baking sheet and place the bell peppers on the sheet with the open-side facing down. Bake for 10-12 minutes.
Lightly spray a skillet with Kelapo Coconut Oil and place on medium heat. Add the diced onions.
Add ground wild game meat to the skillet. When the meat is nearly finished, add in beans, fresh parsley, 2 heaping tbsp of pico de gallo, salsa, or diced tomatoes. Mix with a spatula.
Remove the bell peppers from the oven and flip them over. Add in game and beans mixture. Top with goat cheese (or low fat mozzarella cheese) and fresh parsley (if desired)
Bake in the oven for 8-10 minutes.", user_id: 1)

Meal.create(meal:"	SPICY FLANK STEAK KABOBS WITH SWEET POTATO", ingredients: "FLANK STEAK 5 OZ,
SWEET POTATO 1 SMALL,
ZUCCHINI 1/2 MEDIUM,
BELL PEPPER 1,
SEASONING,
BLUEBERRIES 1/8 CUP,
SHAVED ALMONDS 1 TBSP,
RAW ORGANIC HONEY 1 TBSP,
CHERRIES", directions: "Set oven to 405°F.
Wrap the sweet potato in foil and place in the oven. If you cannot find a whole sweet potato close to your serving size, then simply cut the sweet potato into small pieces, measure them to ensure your serving size portion and bake them on a baking sheet lined with aluminum foil. Bake for about 45 minutes depending on the size. If they are cut in chunks, then bake for only 25-30 minutes.
Cut flank steak into very small pieces. Season with your choice of seasonings.
Chop 1 zucchini and 1 bell pepper into small pieces for the kabob.
Assemble the kabobs, alternating between beef, bell pepper, and zucchini.
Place the assembled kabob on a baking sheet/pan and bake for 8-12 minutes depending how well you like your meat cooked.", user_id: 1)

Meal.create(meal: "TURKEY MEATLOAF WITH SPINACH AND WHOLE WHEAT PEARL", ingredients: "
GROUND TURKEY 5 OZ,
RED ONIONS 3/4 CUP,
MARINARA SAUCE 1/3 CUP,
SPINACH1 CUP RAW,
SEASONINGS PARSLEY, BASIL, GARLIC, ONION, DASH OF CORIANDER, PEPPER, SEA SALT (PINCH),
COUSCOUS 1/2 CUP,
OLIVE OIL 1 TBSP,
PINEAPPLE", directions: "Set oven to 405°F.
Season ground turkey with your choice of seasonings. Add in your choice of diced veggies.
Lightly spray your muffin pan with Kelapo Coconut Oil. Place the ground turkey inside of the muffin holders. Depending on how big your muffin pan is and your singular serving, you may have to use 2 muffin holders for each serving.
Top each serving with 1 tbsp marinara sauce.
Bake in the oven for about 8-10 minutes. If you use less lean ground turkey, you can consider increasing the cooking time to 10-12 minutes.
Boil couscous using water and low sodium chicken or vegetable broth. Add cilantro or onions while cooking for added flavor. Set aside, and allow to cool. Add 1 tbsp olive tapenade to couscous if desired.", user_id: 1)

Meal.create(meal: "6	SESAME TAHINI SHRIMP AND ZUCCHINI LINGUINE PASTA SALAD", ingredients: "
SHRIMP 6 OZ,
LARGE ZUCCHINI 1 LARGE,
BELL PEPPERS 1.5 CUP SLICED,
ROASTED TAHINI BUTTER 1 TBSP,
SESAME SEEDS 1/2 TBSP,
BLUEBERRIES OPTIONAL", directions: "Cut zucchini using a Julienne shredder in order to make the raw linguine.
Slice veggies for pasta.
In a bowl, mix tahini, sesame oil and Bragg's Liquid Aminos.
Place all ingredients into a large bowl, including cooked shrimp. Pour the Tahini sauce you made over the meal. Toss it to make sure all sides are covered in the sauce.
Sprinkle sesame seeds on top. And then devour!", user_id: 1)